### PR TITLE
Implements difficulty level.

### PR DESCRIPTION
**Pull request by itrajkov**
- Easy - random moves
- Intermediate - score algorithm with 2 random directions
- Hard - score algorithm with all directions
- Impossible - minmax `depth=6`
- Godmode - minmax `depth=7`

### CODE REVIEW

**Comment by itrajkov** [comment]
Addresses #12

**Comment by JustA3DObject** [comment]
> Addresses #12 

I guess your fork was behind some comments from the main branch so your PR has merge conflicts. Could you look into it please?

**Comment by JustA3DObject** [comment]
The branch still has merge conflicts. Try to resolve them please.

**Comment by itrajkov** [comment]
Yeah I will, just haven't had the time

**Comment by itrajkov** [comment]
Conflicts resolved, also added a few bug fixes and casing fixes.

**Pull request merged**
